
FROM node:10.15-alpine

RUN apk add --no-cache bash

WORKDIR '/home/dineshs/teezle/workspace/docker/Reentry/react-app/dev-app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]
